import { Inter } from "next/font/google";
import Navigation from "./Navigation";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: `Jack's Website`,
  description: `Generated by jack`,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-gradient-to-r from-gray-300 dark:from-gray-800 to-gray-400 dark:to-gray-900 font-mono text-gray-800 dark:text-gray-300 min-h-screen">
          <div className="text-center">
            <Link href="/"><h1 className="text-5xl dark:text-shadow-md py-5">Jack&apos;s Website</h1></Link>
            <Navigation />
            <hr className="border-2 dark:border-gray-600" />
          </div>
          {children}
          <div className="text-center mt-5">
            <p>&copy; 2023 Retro Blog. All rights reserved.</p>
          </div>
        </div>
      </body>
    </html>
  );
}
